### ISSUE TITLE
New version :)

### ISSUE THREAD

**Issue by Shuunen** [feryardiant/fineuploader-dist#3]
Hi,

Is it possible to bump the version ?

Thanks for your repo, it sucks that FineUploader team does not commit the dist on their repo !

**Comment by feryardiant** [comment]
Hi @Shuunen 

Sure and sorry for being late, my hand still on another project right now. Wait until this afternoon (GMT+7)

Thanks for the reminder :smile:

**Comment by Shuunen** [comment]
Great thanks :)

**Comment by feryardiant** [comment]
Done!

I've also update the README.md to make easier build for everyone who wanna contribute this repo.

Cheers :grin:

**Comment by Shuunen** [comment]
thanks for your work
